version: 0.0
os: linux
files:
  - source: webapp-sample/
    destination: /var/www/html/
    overwrite: true
file_exists_behavior: OVERWRITE
branch_config:
    wip\/.*: ~ 
    main:
        deploymentGroupName: DemoDeploymentG-staging
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::026090560198:role/PIP3-Codedeploy
