name: Deploy Application

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: development
            appspec: appspec-development.yml
          - environment: staging
            appspec: appspec-staging.yml
          - environment: production
            appspec: appspec-production.yml
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          
      - name: Copy the Correct AppSpec File
        run: cp ./${{ matrix.appspec }} ./appspec.yml

      - name: Confirm AppSpec File
        run: cat ./appspec.yml

      - name: Deploy to ${{ matrix.environment }}
        id: deploy
        uses: webfactory/create-aws-codedeploy-deployment@v0.2.2
        with:
          application: DemoApp
          deployment-group: ${{ matrix.deployment_group }}
          deployment-config-name: CodeDeployDefault.OneAtATime
          revision-location: './${{ matrix.appspec }}'
