name: Deploy Application

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, staging, production]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: Deploy to ${{ matrix.environment }}
        id: deploy
        uses: webfactory/create-aws-codedeploy-deployment@v0.2.2
        with:
          application: DemoApp
          deployment-group: DemoDeploymentG-${{ matrix.environment }}
          deployment-config-name: CodeDeployDefault.OneAtATime
          revision-location: 's3://your-s3-bucket/path/to/appspec.yml'
